-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity shift_left_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_size_read : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_r_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_r_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_r_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_r_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_r_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_phi_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_phi_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_phi_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_phi_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_phi_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_z_s_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arrayHLS_TMTT_StubHLS_data_z_s_ce0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_z_s_we0 : OUT STD_LOGIC;
    arrayHLS_TMTT_StubHLS_data_z_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayHLS_TMTT_StubHLS_data_z_s_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    idx_read : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of shift_left_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal i_fu_661_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_reg_740 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln134_fu_656_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_0_reg_646 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal zext_ln135_1_fu_667_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln135_fu_697_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_0_reg_646_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                i_0_reg_646 <= i_reg_740;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_reg_646 <= idx_read;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln134_fu_656_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                i_reg_740 <= i_fu_661_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln134_fu_656_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln134_fu_656_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln134_fu_656_p2)
    begin
        if ((((icmp_ln134_fu_656_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln134_fu_656_p2)
    begin
        if (((icmp_ln134_fu_656_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_d0 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_q0;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_d0 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_q0;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_d0 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_q0;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_d0 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_q0;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_d0 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_q0;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_d0 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_q0;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_d0 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_q0;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_d0 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_q0;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_d0 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_q0;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_d0 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_q0;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_d0 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_q0;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_d0 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_q0;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_d0 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_q0;

    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_phi_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_phi_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_phi_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_phi_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_phi_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_phi_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_phi_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_phi_s_d0 <= arrayHLS_TMTT_StubHLS_data_phi_s_q0;

    arrayHLS_TMTT_StubHLS_data_phi_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_phi_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_phi_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_r_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_r_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_r_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_r_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_r_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_r_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_r_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_r_s_d0 <= arrayHLS_TMTT_StubHLS_data_r_s_q0;

    arrayHLS_TMTT_StubHLS_data_r_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_r_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_r_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_d0 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_q0;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_d0 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_q0;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_d0 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_q0;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_d0 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_q0;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_d0 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_q0;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_d0 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_q0;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_d0 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_q0;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_d0 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_q0;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_d0 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_q0;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_d0 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_q0;

    arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_z_s_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln135_1_fu_667_p1, zext_ln135_fu_697_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_z_s_address0 <= zext_ln135_fu_697_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arrayHLS_TMTT_StubHLS_data_z_s_address0 <= zext_ln135_1_fu_667_p1(4 - 1 downto 0);
        else 
            arrayHLS_TMTT_StubHLS_data_z_s_address0 <= "XXXX";
        end if; 
    end process;


    arrayHLS_TMTT_StubHLS_data_z_s_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            arrayHLS_TMTT_StubHLS_data_z_s_ce0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_z_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arrayHLS_TMTT_StubHLS_data_z_s_d0 <= arrayHLS_TMTT_StubHLS_data_z_s_q0;

    arrayHLS_TMTT_StubHLS_data_z_s_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arrayHLS_TMTT_StubHLS_data_z_s_we0 <= ap_const_logic_1;
        else 
            arrayHLS_TMTT_StubHLS_data_z_s_we0 <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_661_p2 <= std_logic_vector(unsigned(i_0_reg_646) + unsigned(ap_const_lv32_1));
    icmp_ln134_fu_656_p2 <= "1" when (unsigned(i_0_reg_646) < unsigned(arrayHLS_TMTT_StubHLS_size_read)) else "0";
    zext_ln135_1_fu_667_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_661_p2),64));
    zext_ln135_fu_697_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_reg_646),64));
end behav;
