// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module shift_left (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        arrayHLS_TMTT_StubHLS_size_read,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_ce0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_we0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_d0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_q0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_offset,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_ce0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_we0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_d0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_q0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_ce0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_we0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_d0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_q0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_ce0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_we0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_d0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_q0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_ce0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_we0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_d0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_q0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_ce0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_we0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_d0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_q0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_ce0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_we0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_d0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_q0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_ce0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_we0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_d0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_q0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_ce0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_we0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_d0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_q0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_ce0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_we0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_d0,
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_q0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_ce0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_we0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_d0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_q0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_ce0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_we0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_d0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_q0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_ce0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_we0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_d0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_q0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_ce0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_we0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_d0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_q0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_ce0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_we0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_d0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_q0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_ce0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_we0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_d0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_q0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_ce0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_we0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_d0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_q0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_ce0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_we0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_d0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_q0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_ce0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_we0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_d0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_q0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_ce0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_we0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_d0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_q0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_ce0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_we0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_d0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_q0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_ce0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_we0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_d0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_q0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_ce0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_we0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_d0,
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_q0,
        arrayHLS_TMTT_StubHLS_data_r_s_address0,
        arrayHLS_TMTT_StubHLS_data_r_s_ce0,
        arrayHLS_TMTT_StubHLS_data_r_s_we0,
        arrayHLS_TMTT_StubHLS_data_r_s_d0,
        arrayHLS_TMTT_StubHLS_data_r_s_q0,
        arrayHLS_TMTT_StubHLS_data_phi_s_address0,
        arrayHLS_TMTT_StubHLS_data_phi_s_ce0,
        arrayHLS_TMTT_StubHLS_data_phi_s_we0,
        arrayHLS_TMTT_StubHLS_data_phi_s_d0,
        arrayHLS_TMTT_StubHLS_data_phi_s_q0,
        arrayHLS_TMTT_StubHLS_data_z_s_address0,
        arrayHLS_TMTT_StubHLS_data_z_s_ce0,
        arrayHLS_TMTT_StubHLS_data_z_s_we0,
        arrayHLS_TMTT_StubHLS_data_z_s_d0,
        arrayHLS_TMTT_StubHLS_data_z_s_q0,
        idx_read
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] arrayHLS_TMTT_StubHLS_size_read;
output  [8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_q0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_offset;
output  [8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_we0;
output  [0:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_d0;
input  [0:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_we0;
output  [0:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_d0;
input  [0:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_r_s_address0;
output   arrayHLS_TMTT_StubHLS_data_r_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_r_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_r_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_r_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_phi_s_address0;
output   arrayHLS_TMTT_StubHLS_data_phi_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_phi_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_phi_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_phi_s_q0;
output  [8:0] arrayHLS_TMTT_StubHLS_data_z_s_address0;
output   arrayHLS_TMTT_StubHLS_data_z_s_ce0;
output   arrayHLS_TMTT_StubHLS_data_z_s_we0;
output  [31:0] arrayHLS_TMTT_StubHLS_data_z_s_d0;
input  [31:0] arrayHLS_TMTT_StubHLS_data_z_s_q0;
input  [31:0] idx_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_r_s_address0;
reg arrayHLS_TMTT_StubHLS_data_r_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_r_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_phi_s_address0;
reg arrayHLS_TMTT_StubHLS_data_phi_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_phi_s_we0;
reg[8:0] arrayHLS_TMTT_StubHLS_data_z_s_address0;
reg arrayHLS_TMTT_StubHLS_data_z_s_ce0;
reg arrayHLS_TMTT_StubHLS_data_z_s_we0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [9:0] zext_ln135_2_cast_fu_645_p3;
reg   [9:0] zext_ln135_2_cast_reg_748;
wire   [9:0] trunc_ln135_fu_658_p1;
reg   [9:0] trunc_ln135_reg_757;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln134_fu_653_p2;
wire   [31:0] i_fu_662_p2;
reg   [31:0] i_reg_762;
wire   [9:0] trunc_ln135_1_fu_668_p1;
reg   [9:0] trunc_ln135_1_reg_767;
wire   [9:0] add_ln135_fu_672_p2;
reg   [9:0] add_ln135_reg_772;
wire    ap_CS_fsm_state3;
wire   [9:0] add_ln135_2_fu_676_p2;
reg   [9:0] add_ln135_2_reg_777;
wire    ap_CS_fsm_state4;
reg   [31:0] arrayHLS_data_setti_50_reg_912;
wire    ap_CS_fsm_state5;
reg   [31:0] arrayHLS_data_setti_51_reg_917;
reg   [31:0] arrayHLS_data_setti_52_reg_922;
reg   [31:0] arrayHLS_data_setti_53_reg_927;
reg   [31:0] arrayHLS_data_setti_54_reg_932;
reg   [31:0] arrayHLS_data_setti_55_reg_937;
reg   [31:0] arrayHLS_data_setti_56_reg_942;
reg   [31:0] arrayHLS_data_setti_57_reg_947;
reg   [31:0] arrayHLS_data_setti_58_reg_952;
reg   [31:0] arrayHLS_data_setti_59_reg_957;
reg   [31:0] arrayHLS_data_modul_64_reg_962;
reg   [31:0] arrayHLS_data_modul_65_reg_967;
reg   [31:0] arrayHLS_data_modul_66_reg_972;
reg   [31:0] arrayHLS_data_modul_67_reg_977;
reg   [31:0] arrayHLS_data_modul_68_reg_982;
reg   [31:0] arrayHLS_data_modul_69_reg_987;
reg   [31:0] arrayHLS_data_modul_70_reg_992;
reg   [31:0] arrayHLS_data_modul_71_reg_997;
reg   [31:0] arrayHLS_data_modul_72_reg_1002;
reg   [31:0] arrayHLS_data_modul_73_reg_1007;
reg   [0:0] arrayHLS_data_modul_74_reg_1012;
reg   [0:0] arrayHLS_data_modul_75_reg_1017;
reg   [31:0] arrayHLS_data_modul_76_reg_1022;
reg   [31:0] arrayHLS_data_r_lo_reg_1027;
reg   [31:0] arrayHLS_data_phi_4_reg_1032;
reg   [31:0] arrayHLS_data_z_lo_reg_1037;
reg   [31:0] i_0_reg_632;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln135_2_fu_680_p1;
wire   [63:0] zext_ln135_fu_709_p1;
wire   [5:0] trunc_ln132_fu_641_p1;
reg   [5:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        i_0_reg_632 <= i_reg_762;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_632 <= idx_read;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln135_2_reg_777 <= add_ln135_2_fu_676_p2;
        add_ln135_reg_772 <= add_ln135_fu_672_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        arrayHLS_data_modul_64_reg_962 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_q0;
        arrayHLS_data_modul_65_reg_967 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_q0;
        arrayHLS_data_modul_66_reg_972 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_q0;
        arrayHLS_data_modul_67_reg_977 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_q0;
        arrayHLS_data_modul_68_reg_982 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_q0;
        arrayHLS_data_modul_69_reg_987 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_q0;
        arrayHLS_data_modul_70_reg_992 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_q0;
        arrayHLS_data_modul_71_reg_997 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_q0;
        arrayHLS_data_modul_72_reg_1002 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_q0;
        arrayHLS_data_modul_73_reg_1007 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_q0;
        arrayHLS_data_modul_74_reg_1012 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_q0;
        arrayHLS_data_modul_75_reg_1017 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_q0;
        arrayHLS_data_modul_76_reg_1022 <= arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_q0;
        arrayHLS_data_phi_4_reg_1032 <= arrayHLS_TMTT_StubHLS_data_phi_s_q0;
        arrayHLS_data_r_lo_reg_1027 <= arrayHLS_TMTT_StubHLS_data_r_s_q0;
        arrayHLS_data_setti_50_reg_912 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_q0;
        arrayHLS_data_setti_51_reg_917 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_q0;
        arrayHLS_data_setti_52_reg_922 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_q0;
        arrayHLS_data_setti_53_reg_927 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_q0;
        arrayHLS_data_setti_54_reg_932 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_q0;
        arrayHLS_data_setti_55_reg_937 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_q0;
        arrayHLS_data_setti_56_reg_942 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_q0;
        arrayHLS_data_setti_57_reg_947 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_q0;
        arrayHLS_data_setti_58_reg_952 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_q0;
        arrayHLS_data_setti_59_reg_957 <= arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_q0;
        arrayHLS_data_z_lo_reg_1037 <= arrayHLS_TMTT_StubHLS_data_z_s_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln134_fu_653_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_reg_762 <= i_fu_662_p2;
        trunc_ln135_1_reg_767 <= trunc_ln135_1_fu_668_p1;
        trunc_ln135_reg_757 <= trunc_ln135_fu_658_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        zext_ln135_2_cast_reg_748[9 : 4] <= zext_ln135_2_cast_fu_645_p3[9 : 4];
    end
end

always @ (*) begin
    if ((((icmp_ln134_fu_653_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln134_fu_653_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_phi_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_phi_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_phi_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_phi_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_phi_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_phi_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_phi_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_r_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_r_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_r_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_r_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_r_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_r_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_r_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_z_s_address0 = zext_ln135_fu_709_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        arrayHLS_TMTT_StubHLS_data_z_s_address0 = zext_ln135_2_fu_680_p1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_z_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        arrayHLS_TMTT_StubHLS_data_z_s_ce0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_z_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        arrayHLS_TMTT_StubHLS_data_z_s_we0 = 1'b1;
    end else begin
        arrayHLS_TMTT_StubHLS_data_z_s_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln134_fu_653_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln135_2_fu_676_p2 = (zext_ln135_2_cast_reg_748 + trunc_ln135_1_reg_767);

assign add_ln135_fu_672_p2 = (zext_ln135_2_cast_reg_748 + trunc_ln135_reg_757);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_d0 = arrayHLS_data_modul_74_reg_1012;

assign arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_d0 = arrayHLS_data_modul_76_reg_1022;

assign arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_d0 = arrayHLS_data_modul_75_reg_1017;

assign arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_d0 = arrayHLS_data_modul_70_reg_992;

assign arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_d0 = arrayHLS_data_modul_71_reg_997;

assign arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_d0 = arrayHLS_data_modul_72_reg_1002;

assign arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_d0 = arrayHLS_data_modul_66_reg_972;

assign arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_d0 = arrayHLS_data_modul_65_reg_967;

assign arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_d0 = arrayHLS_data_modul_64_reg_962;

assign arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_d0 = arrayHLS_data_modul_67_reg_977;

assign arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_d0 = arrayHLS_data_modul_68_reg_982;

assign arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_d0 = arrayHLS_data_modul_69_reg_987;

assign arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_d0 = arrayHLS_data_modul_73_reg_1007;

assign arrayHLS_TMTT_StubHLS_data_phi_s_d0 = arrayHLS_data_phi_4_reg_1032;

assign arrayHLS_TMTT_StubHLS_data_r_s_d0 = arrayHLS_data_r_lo_reg_1027;

assign arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_d0 = arrayHLS_data_setti_56_reg_942;

assign arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_d0 = arrayHLS_data_setti_57_reg_947;

assign arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_d0 = arrayHLS_data_setti_58_reg_952;

assign arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_d0 = arrayHLS_data_setti_52_reg_922;

assign arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_d0 = arrayHLS_data_setti_51_reg_917;

assign arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_d0 = arrayHLS_data_setti_50_reg_912;

assign arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_d0 = arrayHLS_data_setti_53_reg_927;

assign arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_d0 = arrayHLS_data_setti_54_reg_932;

assign arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_d0 = arrayHLS_data_setti_55_reg_937;

assign arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_d0 = arrayHLS_data_setti_59_reg_957;

assign arrayHLS_TMTT_StubHLS_data_z_s_d0 = arrayHLS_data_z_lo_reg_1037;

assign i_fu_662_p2 = (32'd1 + i_0_reg_632);

assign icmp_ln134_fu_653_p2 = ((i_0_reg_632 < arrayHLS_TMTT_StubHLS_size_read) ? 1'b1 : 1'b0);

assign trunc_ln132_fu_641_p1 = arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_offset[5:0];

assign trunc_ln135_1_fu_668_p1 = i_fu_662_p2[9:0];

assign trunc_ln135_fu_658_p1 = i_0_reg_632[9:0];

assign zext_ln135_2_cast_fu_645_p3 = {{trunc_ln132_fu_641_p1}, {4'd0}};

assign zext_ln135_2_fu_680_p1 = add_ln135_2_reg_777;

assign zext_ln135_fu_709_p1 = add_ln135_reg_772;

always @ (posedge ap_clk) begin
    zext_ln135_2_cast_reg_748[3:0] <= 4'b0000;
end

endmodule //shift_left
