// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _calcHelix_HH_
#define _calcHelix_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "LR_top_fsub_32ns_32ns_32_10_full_dsp_1.h"
#include "LR_top_fmul_32ns_32ns_32_6_max_dsp_1.h"
#include "LR_top_fcmp_32ns_32ns_1_3_1.h"

namespace ap_rtl {

struct calcHelix : public sc_module {
    // Port declarations 24
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > LRHLS_settings_chosenRofPhi_read;
    sc_in< sc_lv<32> > LRHLS_HTParameter_qOverPt_read;
    sc_in< sc_lv<32> > LRHLS_HTParameter_phiT_read;
    sc_in< sc_lv<32> > LRHLS_stubMap_size_read;
    sc_out< sc_lv<5> > LRHLS_stubMap_data_second_size_s_address0;
    sc_out< sc_logic > LRHLS_stubMap_data_second_size_s_ce0;
    sc_in< sc_lv<32> > LRHLS_stubMap_data_second_size_s_q0;
    sc_out< sc_lv<9> > LRHLS_stubMap_data_second_data_r_s_address0;
    sc_out< sc_logic > LRHLS_stubMap_data_second_data_r_s_ce0;
    sc_in< sc_lv<32> > LRHLS_stubMap_data_second_data_r_s_q0;
    sc_out< sc_lv<9> > LRHLS_stubMap_data_second_data_phi_s_address0;
    sc_out< sc_logic > LRHLS_stubMap_data_second_data_phi_s_ce0;
    sc_in< sc_lv<32> > LRHLS_stubMap_data_second_data_phi_s_q0;
    sc_in< sc_lv<1> > guard_variable_for_f_i;
    sc_out< sc_lv<1> > guard_variable_for_f_o;
    sc_out< sc_logic > guard_variable_for_f_o_ap_vld;
    sc_out< sc_lv<32> > n;
    sc_out< sc_logic > n_ap_vld;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    calcHelix(sc_module_name name);
    SC_HAS_PROCESS(calcHelix);

    ~calcHelix();

    sc_trace_file* mVcdFile;

    LR_top_fsub_32ns_32ns_32_10_full_dsp_1<1,10,32,32,32>* LR_top_fsub_32ns_32ns_32_10_full_dsp_1_U1134;
    LR_top_fsub_32ns_32ns_32_10_full_dsp_1<1,10,32,32,32>* LR_top_fsub_32ns_32ns_32_10_full_dsp_1_U1135;
    LR_top_fmul_32ns_32ns_32_6_max_dsp_1<1,6,32,32,32>* LR_top_fmul_32ns_32ns_32_6_max_dsp_1_U1136;
    LR_top_fcmp_32ns_32ns_1_3_1<1,3,32,32,1>* LR_top_fcmp_32ns_32ns_1_3_1_U1137;
    sc_signal< sc_lv<44> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > grp_fu_135_p2;
    sc_signal< sc_lv<32> > reg_154;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_logic > ap_CS_fsm_state32;
    sc_signal< sc_lv<10> > p_cast3_fu_169_p3;
    sc_signal< sc_lv<10> > p_cast3_reg_354;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > add_ln106_fu_182_p2;
    sc_signal< sc_lv<32> > add_ln106_reg_362;
    sc_signal< sc_lv<1> > icmp_ln106_fu_177_p2;
    sc_signal< sc_lv<32> > LRHLS_stubMap_data_57_reg_372;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > icmp_ln162_fu_188_p2;
    sc_signal< sc_lv<1> > icmp_ln162_reg_377;
    sc_signal< sc_lv<9> > LRHLS_stubMap_data_58_reg_381;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<9> > LRHLS_stubMap_data_59_reg_386;
    sc_signal< sc_lv<32> > add_ln111_fu_214_p2;
    sc_signal< sc_lv<32> > add_ln111_reg_394;
    sc_signal< sc_lv<32> > LRHLS_stubMap_data_60_reg_399;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<32> > LRHLS_stubMap_data_61_reg_404;
    sc_signal< sc_lv<32> > grp_fu_139_p2;
    sc_signal< sc_lv<32> > tmp_s_reg_409;
    sc_signal< sc_lv<32> > grp_fu_143_p2;
    sc_signal< sc_lv<32> > tmp_14_reg_414;
    sc_signal< sc_logic > ap_CS_fsm_state22;
    sc_signal< sc_lv<1> > grp_fu_148_p2;
    sc_signal< sc_lv<1> > tmp_19_reg_419;
    sc_signal< sc_logic > ap_CS_fsm_state35;
    sc_signal< sc_lv<32> > select_ln32_fu_271_p3;
    sc_signal< sc_lv<32> > select_ln32_reg_424;
    sc_signal< sc_logic > ap_CS_fsm_state36;
    sc_signal< sc_lv<1> > icmp_ln40_fu_296_p2;
    sc_signal< sc_lv<1> > icmp_ln40_reg_430;
    sc_signal< sc_logic > ap_CS_fsm_state37;
    sc_signal< sc_lv<1> > icmp_ln40_3_fu_302_p2;
    sc_signal< sc_lv<1> > icmp_ln40_3_reg_435;
    sc_signal< sc_lv<1> > and_ln40_fu_312_p2;
    sc_signal< sc_lv<1> > and_ln40_reg_440;
    sc_signal< sc_logic > ap_CS_fsm_state39;
    sc_signal< sc_lv<1> > guard_variable_for_f_3_load_fu_318_p1;
    sc_signal< sc_lv<1> > guard_variable_for_f_3_reg_444;
    sc_signal< sc_lv<32> > p_begin_0_rec_reg_113;
    sc_signal< sc_lv<1> > icmp_ln111_fu_209_p2;
    sc_signal< sc_lv<32> > p_begin2_0_rec_reg_124;
    sc_signal< sc_logic > ap_CS_fsm_state44;
    sc_signal< sc_lv<64> > zext_ln106_fu_160_p1;
    sc_signal< sc_lv<64> > p_cast_fu_203_p1;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<32> > grp_fu_135_p0;
    sc_signal< sc_lv<32> > grp_fu_135_p1;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_logic > ap_CS_fsm_state23;
    sc_signal< sc_lv<32> > grp_fu_143_p1;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_lv<32> > grp_fu_148_p0;
    sc_signal< sc_lv<32> > grp_fu_148_p1;
    sc_signal< sc_logic > ap_CS_fsm_state33;
    sc_signal< sc_lv<6> > trunc_ln106_fu_165_p1;
    sc_signal< sc_lv<10> > empty_fu_194_p1;
    sc_signal< sc_lv<10> > empty_20_fu_198_p2;
    sc_signal< sc_lv<32> > bitcast_ln32_fu_220_p1;
    sc_signal< sc_lv<8> > tmp_fu_224_p4;
    sc_signal< sc_lv<23> > trunc_ln32_fu_234_p1;
    sc_signal< sc_lv<1> > icmp_ln32_8_fu_244_p2;
    sc_signal< sc_lv<1> > icmp_ln32_fu_238_p2;
    sc_signal< sc_lv<1> > or_ln32_fu_250_p2;
    sc_signal< sc_lv<32> > xor_ln33_fu_261_p2;
    sc_signal< sc_lv<1> > and_ln32_fu_256_p2;
    sc_signal< sc_lv<32> > bitcast_ln33_fu_267_p1;
    sc_signal< sc_lv<32> > bitcast_ln40_fu_279_p1;
    sc_signal< sc_lv<8> > tmp_20_fu_282_p4;
    sc_signal< sc_lv<23> > trunc_ln40_fu_292_p1;
    sc_signal< sc_lv<1> > or_ln40_fu_308_p2;
    sc_signal< sc_lv<5> > grp_fu_148_opcode;
    sc_signal< sc_lv<44> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<44> ap_ST_fsm_state1;
    static const sc_lv<44> ap_ST_fsm_state2;
    static const sc_lv<44> ap_ST_fsm_state3;
    static const sc_lv<44> ap_ST_fsm_state4;
    static const sc_lv<44> ap_ST_fsm_state5;
    static const sc_lv<44> ap_ST_fsm_state6;
    static const sc_lv<44> ap_ST_fsm_state7;
    static const sc_lv<44> ap_ST_fsm_state8;
    static const sc_lv<44> ap_ST_fsm_state9;
    static const sc_lv<44> ap_ST_fsm_state10;
    static const sc_lv<44> ap_ST_fsm_state11;
    static const sc_lv<44> ap_ST_fsm_state12;
    static const sc_lv<44> ap_ST_fsm_state13;
    static const sc_lv<44> ap_ST_fsm_state14;
    static const sc_lv<44> ap_ST_fsm_state15;
    static const sc_lv<44> ap_ST_fsm_state16;
    static const sc_lv<44> ap_ST_fsm_state17;
    static const sc_lv<44> ap_ST_fsm_state18;
    static const sc_lv<44> ap_ST_fsm_state19;
    static const sc_lv<44> ap_ST_fsm_state20;
    static const sc_lv<44> ap_ST_fsm_state21;
    static const sc_lv<44> ap_ST_fsm_state22;
    static const sc_lv<44> ap_ST_fsm_state23;
    static const sc_lv<44> ap_ST_fsm_state24;
    static const sc_lv<44> ap_ST_fsm_state25;
    static const sc_lv<44> ap_ST_fsm_state26;
    static const sc_lv<44> ap_ST_fsm_state27;
    static const sc_lv<44> ap_ST_fsm_state28;
    static const sc_lv<44> ap_ST_fsm_state29;
    static const sc_lv<44> ap_ST_fsm_state30;
    static const sc_lv<44> ap_ST_fsm_state31;
    static const sc_lv<44> ap_ST_fsm_state32;
    static const sc_lv<44> ap_ST_fsm_state33;
    static const sc_lv<44> ap_ST_fsm_state34;
    static const sc_lv<44> ap_ST_fsm_state35;
    static const sc_lv<44> ap_ST_fsm_state36;
    static const sc_lv<44> ap_ST_fsm_state37;
    static const sc_lv<44> ap_ST_fsm_state38;
    static const sc_lv<44> ap_ST_fsm_state39;
    static const sc_lv<44> ap_ST_fsm_state40;
    static const sc_lv<44> ap_ST_fsm_state41;
    static const sc_lv<44> ap_ST_fsm_state42;
    static const sc_lv<44> ap_ST_fsm_state43;
    static const sc_lv<44> ap_ST_fsm_state44;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_22;
    static const sc_lv<32> ap_const_lv32_23;
    static const sc_lv<32> ap_const_lv32_24;
    static const sc_lv<32> ap_const_lv32_26;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2B;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_3E22F983;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_40490FDB;
    static const sc_lv<32> ap_const_lv32_20;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<32> ap_const_lv32_80000000;
    static const sc_lv<5> ap_const_lv5_4;
    static const sc_lv<5> ap_const_lv5_5;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_LRHLS_stubMap_data_second_data_phi_s_address0();
    void thread_LRHLS_stubMap_data_second_data_phi_s_ce0();
    void thread_LRHLS_stubMap_data_second_data_r_s_address0();
    void thread_LRHLS_stubMap_data_second_data_r_s_ce0();
    void thread_LRHLS_stubMap_data_second_size_s_address0();
    void thread_LRHLS_stubMap_data_second_size_s_ce0();
    void thread_add_ln106_fu_182_p2();
    void thread_add_ln111_fu_214_p2();
    void thread_and_ln32_fu_256_p2();
    void thread_and_ln40_fu_312_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state22();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state32();
    void thread_ap_CS_fsm_state33();
    void thread_ap_CS_fsm_state35();
    void thread_ap_CS_fsm_state36();
    void thread_ap_CS_fsm_state37();
    void thread_ap_CS_fsm_state39();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state44();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_bitcast_ln32_fu_220_p1();
    void thread_bitcast_ln33_fu_267_p1();
    void thread_bitcast_ln40_fu_279_p1();
    void thread_empty_20_fu_198_p2();
    void thread_empty_fu_194_p1();
    void thread_grp_fu_135_p0();
    void thread_grp_fu_135_p1();
    void thread_grp_fu_143_p1();
    void thread_grp_fu_148_opcode();
    void thread_grp_fu_148_p0();
    void thread_grp_fu_148_p1();
    void thread_guard_variable_for_f_3_load_fu_318_p1();
    void thread_guard_variable_for_f_o();
    void thread_guard_variable_for_f_o_ap_vld();
    void thread_icmp_ln106_fu_177_p2();
    void thread_icmp_ln111_fu_209_p2();
    void thread_icmp_ln162_fu_188_p2();
    void thread_icmp_ln32_8_fu_244_p2();
    void thread_icmp_ln32_fu_238_p2();
    void thread_icmp_ln40_3_fu_302_p2();
    void thread_icmp_ln40_fu_296_p2();
    void thread_n();
    void thread_n_ap_vld();
    void thread_or_ln32_fu_250_p2();
    void thread_or_ln40_fu_308_p2();
    void thread_p_cast3_fu_169_p3();
    void thread_p_cast_fu_203_p1();
    void thread_select_ln32_fu_271_p3();
    void thread_tmp_20_fu_282_p4();
    void thread_tmp_fu_224_p4();
    void thread_trunc_ln106_fu_165_p1();
    void thread_trunc_ln32_fu_234_p1();
    void thread_trunc_ln40_fu_292_p1();
    void thread_xor_ln33_fu_261_p2();
    void thread_zext_ln106_fu_160_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
