// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "shift_left.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic shift_left::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic shift_left::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> shift_left::ap_ST_fsm_state1 = "1";
const sc_lv<6> shift_left::ap_ST_fsm_state2 = "10";
const sc_lv<6> shift_left::ap_ST_fsm_state3 = "100";
const sc_lv<6> shift_left::ap_ST_fsm_state4 = "1000";
const sc_lv<6> shift_left::ap_ST_fsm_state5 = "10000";
const sc_lv<6> shift_left::ap_ST_fsm_state6 = "100000";
const sc_lv<32> shift_left::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> shift_left::ap_const_lv32_1 = "1";
const sc_lv<1> shift_left::ap_const_lv1_1 = "1";
const sc_lv<32> shift_left::ap_const_lv32_2 = "10";
const sc_lv<32> shift_left::ap_const_lv32_3 = "11";
const sc_lv<32> shift_left::ap_const_lv32_4 = "100";
const sc_lv<32> shift_left::ap_const_lv32_5 = "101";
const sc_lv<4> shift_left::ap_const_lv4_0 = "0000";
const sc_lv<1> shift_left::ap_const_lv1_0 = "0";
const bool shift_left::ap_const_boolean_1 = true;

shift_left::shift_left(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln135_2_fu_676_p2);
    sensitive << ( zext_ln135_2_cast_reg_748 );
    sensitive << ( trunc_ln135_1_reg_767 );

    SC_METHOD(thread_add_ln135_fu_672_p2);
    sensitive << ( zext_ln135_2_cast_reg_748 );
    sensitive << ( trunc_ln135_reg_757 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln134_fu_653_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln134_fu_653_p2 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_d0);
    sensitive << ( arrayHLS_data_modul_74_reg_1012 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_d0);
    sensitive << ( arrayHLS_data_modul_76_reg_1022 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_d0);
    sensitive << ( arrayHLS_data_modul_75_reg_1017 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_d0);
    sensitive << ( arrayHLS_data_modul_70_reg_992 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_d0);
    sensitive << ( arrayHLS_data_modul_71_reg_997 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_d0);
    sensitive << ( arrayHLS_data_modul_72_reg_1002 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_d0);
    sensitive << ( arrayHLS_data_modul_66_reg_972 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_d0);
    sensitive << ( arrayHLS_data_modul_65_reg_967 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_d0);
    sensitive << ( arrayHLS_data_modul_64_reg_962 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_d0);
    sensitive << ( arrayHLS_data_modul_67_reg_977 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_d0);
    sensitive << ( arrayHLS_data_modul_68_reg_982 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_d0);
    sensitive << ( arrayHLS_data_modul_69_reg_987 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_d0);
    sensitive << ( arrayHLS_data_modul_73_reg_1007 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_phi_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_phi_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_phi_s_d0);
    sensitive << ( arrayHLS_data_phi_4_reg_1032 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_phi_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_r_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_r_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_r_s_d0);
    sensitive << ( arrayHLS_data_r_lo_reg_1027 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_r_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_d0);
    sensitive << ( arrayHLS_data_setti_56_reg_942 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_d0);
    sensitive << ( arrayHLS_data_setti_57_reg_947 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_d0);
    sensitive << ( arrayHLS_data_setti_58_reg_952 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_d0);
    sensitive << ( arrayHLS_data_setti_52_reg_922 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_d0);
    sensitive << ( arrayHLS_data_setti_51_reg_917 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_d0);
    sensitive << ( arrayHLS_data_setti_50_reg_912 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_d0);
    sensitive << ( arrayHLS_data_setti_53_reg_927 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_d0);
    sensitive << ( arrayHLS_data_setti_54_reg_932 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_d0);
    sensitive << ( arrayHLS_data_setti_55_reg_937 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_d0);
    sensitive << ( arrayHLS_data_setti_59_reg_957 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_z_s_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln135_2_fu_680_p1 );
    sensitive << ( zext_ln135_fu_709_p1 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_z_s_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_z_s_d0);
    sensitive << ( arrayHLS_data_z_lo_reg_1037 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_arrayHLS_TMTT_StubHLS_data_z_s_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_i_fu_662_p2);
    sensitive << ( i_0_reg_632 );

    SC_METHOD(thread_icmp_ln134_fu_653_p2);
    sensitive << ( arrayHLS_TMTT_StubHLS_size_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_632 );

    SC_METHOD(thread_trunc_ln132_fu_641_p1);
    sensitive << ( arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_offset );

    SC_METHOD(thread_trunc_ln135_1_fu_668_p1);
    sensitive << ( i_fu_662_p2 );

    SC_METHOD(thread_trunc_ln135_fu_658_p1);
    sensitive << ( i_0_reg_632 );

    SC_METHOD(thread_zext_ln135_2_cast_fu_645_p3);
    sensitive << ( trunc_ln132_fu_641_p1 );

    SC_METHOD(thread_zext_ln135_2_fu_680_p1);
    sensitive << ( add_ln135_2_reg_777 );

    SC_METHOD(thread_zext_ln135_fu_709_p1);
    sensitive << ( add_ln135_reg_772 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln134_fu_653_p2 );

    ap_CS_fsm = "000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "shift_left_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_size_read, "(port)arrayHLS_TMTT_StubHLS_size_read");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_offset, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_offset");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_r_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_r_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_r_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_r_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_r_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_r_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_r_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_r_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_r_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_r_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_phi_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_phi_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_phi_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_phi_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_phi_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_phi_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_phi_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_phi_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_phi_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_phi_s_q0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_z_s_address0, "(port)arrayHLS_TMTT_StubHLS_data_z_s_address0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_z_s_ce0, "(port)arrayHLS_TMTT_StubHLS_data_z_s_ce0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_z_s_we0, "(port)arrayHLS_TMTT_StubHLS_data_z_s_we0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_z_s_d0, "(port)arrayHLS_TMTT_StubHLS_data_z_s_d0");
    sc_trace(mVcdFile, arrayHLS_TMTT_StubHLS_data_z_s_q0, "(port)arrayHLS_TMTT_StubHLS_data_z_s_q0");
    sc_trace(mVcdFile, idx_read, "(port)idx_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, zext_ln135_2_cast_fu_645_p3, "zext_ln135_2_cast_fu_645_p3");
    sc_trace(mVcdFile, zext_ln135_2_cast_reg_748, "zext_ln135_2_cast_reg_748");
    sc_trace(mVcdFile, trunc_ln135_fu_658_p1, "trunc_ln135_fu_658_p1");
    sc_trace(mVcdFile, trunc_ln135_reg_757, "trunc_ln135_reg_757");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln134_fu_653_p2, "icmp_ln134_fu_653_p2");
    sc_trace(mVcdFile, i_fu_662_p2, "i_fu_662_p2");
    sc_trace(mVcdFile, i_reg_762, "i_reg_762");
    sc_trace(mVcdFile, trunc_ln135_1_fu_668_p1, "trunc_ln135_1_fu_668_p1");
    sc_trace(mVcdFile, trunc_ln135_1_reg_767, "trunc_ln135_1_reg_767");
    sc_trace(mVcdFile, add_ln135_fu_672_p2, "add_ln135_fu_672_p2");
    sc_trace(mVcdFile, add_ln135_reg_772, "add_ln135_reg_772");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, add_ln135_2_fu_676_p2, "add_ln135_2_fu_676_p2");
    sc_trace(mVcdFile, add_ln135_2_reg_777, "add_ln135_2_reg_777");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, arrayHLS_data_setti_50_reg_912, "arrayHLS_data_setti_50_reg_912");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, arrayHLS_data_setti_51_reg_917, "arrayHLS_data_setti_51_reg_917");
    sc_trace(mVcdFile, arrayHLS_data_setti_52_reg_922, "arrayHLS_data_setti_52_reg_922");
    sc_trace(mVcdFile, arrayHLS_data_setti_53_reg_927, "arrayHLS_data_setti_53_reg_927");
    sc_trace(mVcdFile, arrayHLS_data_setti_54_reg_932, "arrayHLS_data_setti_54_reg_932");
    sc_trace(mVcdFile, arrayHLS_data_setti_55_reg_937, "arrayHLS_data_setti_55_reg_937");
    sc_trace(mVcdFile, arrayHLS_data_setti_56_reg_942, "arrayHLS_data_setti_56_reg_942");
    sc_trace(mVcdFile, arrayHLS_data_setti_57_reg_947, "arrayHLS_data_setti_57_reg_947");
    sc_trace(mVcdFile, arrayHLS_data_setti_58_reg_952, "arrayHLS_data_setti_58_reg_952");
    sc_trace(mVcdFile, arrayHLS_data_setti_59_reg_957, "arrayHLS_data_setti_59_reg_957");
    sc_trace(mVcdFile, arrayHLS_data_modul_64_reg_962, "arrayHLS_data_modul_64_reg_962");
    sc_trace(mVcdFile, arrayHLS_data_modul_65_reg_967, "arrayHLS_data_modul_65_reg_967");
    sc_trace(mVcdFile, arrayHLS_data_modul_66_reg_972, "arrayHLS_data_modul_66_reg_972");
    sc_trace(mVcdFile, arrayHLS_data_modul_67_reg_977, "arrayHLS_data_modul_67_reg_977");
    sc_trace(mVcdFile, arrayHLS_data_modul_68_reg_982, "arrayHLS_data_modul_68_reg_982");
    sc_trace(mVcdFile, arrayHLS_data_modul_69_reg_987, "arrayHLS_data_modul_69_reg_987");
    sc_trace(mVcdFile, arrayHLS_data_modul_70_reg_992, "arrayHLS_data_modul_70_reg_992");
    sc_trace(mVcdFile, arrayHLS_data_modul_71_reg_997, "arrayHLS_data_modul_71_reg_997");
    sc_trace(mVcdFile, arrayHLS_data_modul_72_reg_1002, "arrayHLS_data_modul_72_reg_1002");
    sc_trace(mVcdFile, arrayHLS_data_modul_73_reg_1007, "arrayHLS_data_modul_73_reg_1007");
    sc_trace(mVcdFile, arrayHLS_data_modul_74_reg_1012, "arrayHLS_data_modul_74_reg_1012");
    sc_trace(mVcdFile, arrayHLS_data_modul_75_reg_1017, "arrayHLS_data_modul_75_reg_1017");
    sc_trace(mVcdFile, arrayHLS_data_modul_76_reg_1022, "arrayHLS_data_modul_76_reg_1022");
    sc_trace(mVcdFile, arrayHLS_data_r_lo_reg_1027, "arrayHLS_data_r_lo_reg_1027");
    sc_trace(mVcdFile, arrayHLS_data_phi_4_reg_1032, "arrayHLS_data_phi_4_reg_1032");
    sc_trace(mVcdFile, arrayHLS_data_z_lo_reg_1037, "arrayHLS_data_z_lo_reg_1037");
    sc_trace(mVcdFile, i_0_reg_632, "i_0_reg_632");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, zext_ln135_2_fu_680_p1, "zext_ln135_2_fu_680_p1");
    sc_trace(mVcdFile, zext_ln135_fu_709_p1, "zext_ln135_fu_709_p1");
    sc_trace(mVcdFile, trunc_ln132_fu_641_p1, "trunc_ln132_fu_641_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

shift_left::~shift_left() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void shift_left::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_0_reg_632 = i_reg_762.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_632 = idx_read.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        add_ln135_2_reg_777 = add_ln135_2_fu_676_p2.read();
        add_ln135_reg_772 = add_ln135_fu_672_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        arrayHLS_data_modul_64_reg_962 = arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_q0.read();
        arrayHLS_data_modul_65_reg_967 = arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_q0.read();
        arrayHLS_data_modul_66_reg_972 = arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_q0.read();
        arrayHLS_data_modul_67_reg_977 = arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_q0.read();
        arrayHLS_data_modul_68_reg_982 = arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_q0.read();
        arrayHLS_data_modul_69_reg_987 = arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_q0.read();
        arrayHLS_data_modul_70_reg_992 = arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_q0.read();
        arrayHLS_data_modul_71_reg_997 = arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_q0.read();
        arrayHLS_data_modul_72_reg_1002 = arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_q0.read();
        arrayHLS_data_modul_73_reg_1007 = arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_q0.read();
        arrayHLS_data_modul_74_reg_1012 = arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_q0.read();
        arrayHLS_data_modul_75_reg_1017 = arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_q0.read();
        arrayHLS_data_modul_76_reg_1022 = arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_q0.read();
        arrayHLS_data_phi_4_reg_1032 = arrayHLS_TMTT_StubHLS_data_phi_s_q0.read();
        arrayHLS_data_r_lo_reg_1027 = arrayHLS_TMTT_StubHLS_data_r_s_q0.read();
        arrayHLS_data_setti_50_reg_912 = arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_q0.read();
        arrayHLS_data_setti_51_reg_917 = arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_q0.read();
        arrayHLS_data_setti_52_reg_922 = arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_q0.read();
        arrayHLS_data_setti_53_reg_927 = arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_q0.read();
        arrayHLS_data_setti_54_reg_932 = arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_q0.read();
        arrayHLS_data_setti_55_reg_937 = arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_q0.read();
        arrayHLS_data_setti_56_reg_942 = arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_q0.read();
        arrayHLS_data_setti_57_reg_947 = arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_q0.read();
        arrayHLS_data_setti_58_reg_952 = arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_q0.read();
        arrayHLS_data_setti_59_reg_957 = arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_q0.read();
        arrayHLS_data_z_lo_reg_1037 = arrayHLS_TMTT_StubHLS_data_z_s_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln134_fu_653_p2.read(), ap_const_lv1_1))) {
        i_reg_762 = i_fu_662_p2.read();
        trunc_ln135_1_reg_767 = trunc_ln135_1_fu_668_p1.read();
        trunc_ln135_reg_757 = trunc_ln135_fu_658_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        zext_ln135_2_cast_reg_748 = zext_ln135_2_cast_fu_645_p3.read();
    }
}

void shift_left::thread_add_ln135_2_fu_676_p2() {
    add_ln135_2_fu_676_p2 = (!zext_ln135_2_cast_reg_748.read().is_01() || !trunc_ln135_1_reg_767.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln135_2_cast_reg_748.read()) + sc_biguint<10>(trunc_ln135_1_reg_767.read()));
}

void shift_left::thread_add_ln135_fu_672_p2() {
    add_ln135_fu_672_p2 = (!zext_ln135_2_cast_reg_748.read().is_01() || !trunc_ln135_reg_757.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln135_2_cast_reg_748.read()) + sc_biguint<10>(trunc_ln135_reg_757.read()));
}

void shift_left::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void shift_left::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void shift_left::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void shift_left::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void shift_left::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void shift_left::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void shift_left::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln134_fu_653_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void shift_left::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void shift_left::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln134_fu_653_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_d0() {
    arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_d0 = arrayHLS_data_modul_74_reg_1012.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_barrel_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_d0() {
    arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_d0 = arrayHLS_data_modul_76_reg_1022.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_layerId_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_d0() {
    arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_d0 = arrayHLS_data_modul_75_reg_1017.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_psModule_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_d0() {
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_d0 = arrayHLS_data_modul_70_reg_992.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofPhi_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_d0() {
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_d0 = arrayHLS_data_modul_71_reg_997.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_chosenRofZ_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_d0() {
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_d0 = arrayHLS_data_modul_72_reg_1002.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_invPtToDphi_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_d0() {
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_d0 = arrayHLS_data_modul_66_reg_972.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayersPS_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_d0() {
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_d0 = arrayHLS_data_modul_65_reg_967.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrMinLayers_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_d0() {
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_d0 = arrayHLS_data_modul_64_reg_962.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrNumIterations_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_d0() {
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_d0 = arrayHLS_data_modul_67_reg_977.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidPhi_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_d0() {
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_d0 = arrayHLS_data_modul_68_reg_982.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZ2S_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_d0() {
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_d0 = arrayHLS_data_modul_69_reg_987.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_lrResidZPS_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_d0() {
    arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_d0 = arrayHLS_data_modul_73_reg_1007.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_moduleHLS_settingsHLS_trackerNumLayers_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_phi_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_phi_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_phi_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_phi_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_phi_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_phi_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_phi_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_phi_s_d0() {
    arrayHLS_TMTT_StubHLS_data_phi_s_d0 = arrayHLS_data_phi_4_reg_1032.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_phi_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_phi_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_phi_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_r_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_r_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_r_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_r_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_r_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_r_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_r_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_r_s_d0() {
    arrayHLS_TMTT_StubHLS_data_r_s_d0 = arrayHLS_data_r_lo_reg_1027.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_r_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_r_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_r_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_d0() {
    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_d0 = arrayHLS_data_setti_56_reg_942.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofPhi_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_d0() {
    arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_d0 = arrayHLS_data_setti_57_reg_947.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_chosenRofZ_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_d0() {
    arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_d0 = arrayHLS_data_setti_58_reg_952.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_invPtToDphi_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_d0() {
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_d0 = arrayHLS_data_setti_52_reg_922.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayersPS_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_d0() {
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_d0 = arrayHLS_data_setti_51_reg_917.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrMinLayers_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_d0() {
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_d0 = arrayHLS_data_setti_50_reg_912.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_d0() {
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_d0 = arrayHLS_data_setti_53_reg_927.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidPhi_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_d0() {
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_d0 = arrayHLS_data_setti_54_reg_932.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZ2S_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_d0() {
    arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_d0 = arrayHLS_data_setti_55_reg_937.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_lrResidZPS_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_d0() {
    arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_d0 = arrayHLS_data_setti_59_reg_957.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_settingsHLS_trackerNumLayers_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_z_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_z_s_address0 =  (sc_lv<9>) (zext_ln135_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        arrayHLS_TMTT_StubHLS_data_z_s_address0 =  (sc_lv<9>) (zext_ln135_2_fu_680_p1.read());
    } else {
        arrayHLS_TMTT_StubHLS_data_z_s_address0 = "XXXXXXXXX";
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_z_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        arrayHLS_TMTT_StubHLS_data_z_s_ce0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_z_s_ce0 = ap_const_logic_0;
    }
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_z_s_d0() {
    arrayHLS_TMTT_StubHLS_data_z_s_d0 = arrayHLS_data_z_lo_reg_1037.read();
}

void shift_left::thread_arrayHLS_TMTT_StubHLS_data_z_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        arrayHLS_TMTT_StubHLS_data_z_s_we0 = ap_const_logic_1;
    } else {
        arrayHLS_TMTT_StubHLS_data_z_s_we0 = ap_const_logic_0;
    }
}

void shift_left::thread_i_fu_662_p2() {
    i_fu_662_p2 = (!ap_const_lv32_1.is_01() || !i_0_reg_632.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(i_0_reg_632.read()));
}

void shift_left::thread_icmp_ln134_fu_653_p2() {
    icmp_ln134_fu_653_p2 = (!i_0_reg_632.read().is_01() || !arrayHLS_TMTT_StubHLS_size_read.read().is_01())? sc_lv<1>(): (sc_biguint<32>(i_0_reg_632.read()) < sc_biguint<32>(arrayHLS_TMTT_StubHLS_size_read.read()));
}

void shift_left::thread_trunc_ln132_fu_641_p1() {
    trunc_ln132_fu_641_p1 = arrayHLS_TMTT_StubHLS_data_settingsHLS_lrNumIterations_offset.read().range(6-1, 0);
}

void shift_left::thread_trunc_ln135_1_fu_668_p1() {
    trunc_ln135_1_fu_668_p1 = i_fu_662_p2.read().range(10-1, 0);
}

void shift_left::thread_trunc_ln135_fu_658_p1() {
    trunc_ln135_fu_658_p1 = i_0_reg_632.read().range(10-1, 0);
}

void shift_left::thread_zext_ln135_2_cast_fu_645_p3() {
    zext_ln135_2_cast_fu_645_p3 = esl_concat<6,4>(trunc_ln132_fu_641_p1.read(), ap_const_lv4_0);
}

void shift_left::thread_zext_ln135_2_fu_680_p1() {
    zext_ln135_2_fu_680_p1 = esl_zext<64,10>(add_ln135_2_reg_777.read());
}

void shift_left::thread_zext_ln135_fu_709_p1() {
    zext_ln135_fu_709_p1 = esl_zext<64,10>(add_ln135_reg_772.read());
}

void shift_left::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln134_fu_653_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

}

